### ISSUE TITLE
Website and documentation are offline

### ISSUE THREAD

**Issue by thedoc31** [psf/requests#5214]
Looks like www.python-requests.org and docs.python-requests.org are redirecting to https://2.python-requests.org and failing SSL negotiation, making the site appear down. Google links are all dead, documentation links don't work, etc.

http://2.python-requests.org redirects to https://requests.kennethreitz.org/en/master/, which works.

## Expected Result

Website should appear or redirect to non-HTTPS link

## Actual Result

Redirection to https://2.python-requests.org breaks the site

## Reproduction Steps
Open browser of your choice
Attempt to browse to http://docs.python-requests.org or http://www.python-requests.org.
Browser gets redirect to https://2.python-requests.org which fails with an SSL_PROTOCOL_ERROR

## System Information

N/A

**Comment by CarlosDomingues** [comment]
My first Google result is 2.python-requests.org, which is down. Came here to report this.

**Comment by phvu** [comment]
👍  Same here

Btw, the new logo is cool AF. Kudos.

**Comment by westurner** [comment]
https://requests.readthedocs.io/en/master/ is up.

https://requests.kennethreitz.org/en/master/ is up.

From @kennethreitz https://twitter.com/kennethreitz/status/1176637337553559552 :

> *Been deleting domains for an hour. Down to 26.*

The repo desc and the README both link to https://2.python-requests.org 

@kennethreitz What's with all the whitespace in the README? Why no Kanye pics?

**Comment by Leetcore** [comment]
I opend a pull request for the link change to readthedocs: https://github.com/psf/requests/pull/5216

**Comment by ewdurbin** [comment]
I've updated the link in the readme from #5216 as well as the link at the top of the Github project until @kennethreitz is able to fix python-requests.org. @kennethreitz do you need any assistance with this?

**Comment by jaypeedevlin** [comment]
With (I believe) the same root cause, the search functionality on all (working) versions of the docs (eg https://requests.readthedocs.io/en/master/, https://requests.kennethreitz.org/en/master/) is broken, as all search results link to the old URLs.

**Comment by chmreid** [comment]
Related: #5212

**Comment by nateprewitt** [comment]
This should be resolved now with #5236. Thanks everyone!

**Comment by nateprewitt** [comment]
Actually on second thought, I'm keeping this open till we get the domain fixed. We need to get python-requests.org configured correctly again.

**Comment by nicktimko** [comment]
Chiming in here vs. creating a separate issue as I think it aligns with the work: I would _strongly_ urge that `2.python-requests.org` is fixed/redirected somewhere appropriate. It was "the domain" for months, and a gigantic amount of content was written on blogs, StackOverflow, and more referencing it.

**Comment by mikeobr** [comment]
Additionally anything found using the quick search or "search the docs" routes to removed domains.

**Comment by xmo-odoo** [comment]
@nateprewitt one of the changes in #5236 looks incorrect: https://github.com/psf/requests/pull/5236/files#diff-85987f48f1258d9ee486e3191495582dR384 changes intersphinx mapping of *python* links to requests's RTD (this is used to [embed links to other external docs](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) in such a way that the refs can be tracked and the links updated automatically)

Also not sure whether this change is deployed, but using the quick search box still redirects back to 2.python-requests.org. This looks to be due to [the docsearch snippet](https://github.com/ssbarnea/requests/blob/e1d4fce98b9f0ba4c985496b8d06054afef19b7f/docs/_templates/sidebarlogo.html#L26-L32) which goes through an external API to provide FAYT results, and probably takes over regular submission to jump there as well, since this doesn't really look like the DOM for the normal search box (which should be a self-contained form, there's no form here). Either the PSF should create its own docsearch account and hook into that, or the search field should be reverted to the standard sphinx quicksearch (which would probably require more extensive template work).

There's also [a bunch of tracking and ad code](https://github.com/ssbarnea/requests/blob/e1d4fce98b9f0ba4c985496b8d06054afef19b7f/docs/_templates/hacks.html#L30-L75) in a sibling template, I don't know if it's intentional or leftovers from the original.

**Comment by mrxushang** [comment]
is this drawn by python turtle? if it is, how cool

**Comment by westurner** [comment]
Looks like the RTD version selector now lists versions v1.0.4 through v3.0.0. Thanks!
