### ISSUE TITLE
[FEATURE REQUEST] Fire and forget

### ISSUE THREAD

**Issue by PMLP-novo** [psf/requests#5256]
In my project i need to perform fire and forget for REST-API post and patch calls.

My current solution is:

```
try:
    requests.post(my_uri, params=data
                  timeout=1e-4)
except requests.exceptions.Timeout:
    pass
```
I think a nicer solution could be:
`requests.fire_and_forget(my_uri, method='post', params=data)`
Where method default argument is `'post'`

This feature is requested by other users see this reddit thread 

> https://www.reddit.com/r/learnpython/comments/8ljftm/fire_and_forget_http_request/

My current solution is not perfect since the size of the timeout is relevant. If I set it to 1e-8 and include data it will break before I have sent the data.

**Comment by nicktimko** [comment]
You can't actually "forget" about the connection because you'll need to hold it open, and possibly even wait for TLS negotiation (which requires a few RTT's). Run the connection in a thread, or use async libraries like [aiohttp](https://aiohttp.readthedocs.io/en/stable/client_quickstart.html#make-a-request) or Requests 3 and wrap it in a task (`asyncio.create_task`)

**Comment by nateprewitt** [comment]
Hi @PMLP-novo, the Requests API is frozen right now, so we won’t be adding any new functions at the moment. Thanks for the suggestion!
