### ISSUE TITLE
Session module taking much longer than expected

### ISSUE THREAD

**Issue by unthinkman** [psf/requests#5268]
Session module is running slower than normal requests. 
No errors logged on either side and everything functions properly, but its consistantly 17.5 times slower.  

## Expected Result

s.head(addr) returns in under .01 seconds

## Actual Result

s.head(addr) takes around .1 seconds

## Reproduction Steps

```python
import requests
s=requests.Session()
s.head('http://192.168.0.1:8080/')
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.6.1"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.9"
  },
  "platform": {
    "release": "12.0-RELEASE-p10",
    "system": "FreeBSD"
  },
  "pyOpenSSL": {
    "openssl_version": "1010101f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1010101f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}


send: b'HEAD / HTTP/1.1\r\nHost: 192.168.1.76:8080\r\nUser-Agent: python-requests/2.21.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep
-alive\r\n
session_id=303c361737b70c6a6aacb86896a4900091da7555\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html;charset=utf-8
header: Server: CherryPy/18.3.0
header: Date: Mon, 18 Nov 2019 20:51:08 GMT
header: Allow: GET, HEAD, POST, PUT
header: Content-Length: 2
DEBUG:urllib3.connectionpool:http://192.168.1.76:8080 "HEAD / HTTP/1.1" 200 0
```

**Comment by nateprewitt** [comment]
Hi @unthinkman,

We'd need a lot more information here to see what is going on. If you're looking at [`Requests.head()`](https://github.com/psf/requests/blob/master/requests/api.py#L60-L61) for comparison, it's effectively identical to the code you're using.

If you're trying to compare Requests to another library, we're not actively working on improving Requests speed. Its primary focus is ease of use and has extra overhead to provide that.

I'm going to resolve this for now since there doesn't appear to be anything actionable.
