### ISSUE TITLE
Cannot got parent Session object from Response object

### ISSUE THREAD

**Issue by rgov** [psf/requests#5335]
Since this project has not accepted feature requests for nearly two years, I'll pose this as a bug:

It's very useful to set response hooks on a `Session`. For example:

```python
def check_for_http_error(response, *args, **kwargs):
    response.raise_for_status()

s = requests.Session()
s.hooks['response'] = (check_for_http_error,)
```

Inside my hook, I want to use `response.request.session` or `response.session` to get the associated `Session` object, but I get an `AttributeError` on Requests 2.22.0. It does work to get the `Request` object with `response.request`, though.

I want to do this because I may want to set a custom attribute on my `Session` that is available to my hook. For a simple example, take:

```python
def wait_after(response, *args, **kwargs):
    if response.status_code == requests.codes.ok:
        time.sleep(response.session.delay)  # oops
```

As a workaround to this bug, I can use `functools.partial(wait_after, 1)`, or `functools.partial(set_session, s)`, or use global variables, but most things in Requests are beautiful, and these solutions aren't.

**Comment by nateprewitt** [comment]
Hi @rgov, thanks for the suggestion. Cyclical or complex references like this are something we'd typically try to avoid. They often lead to unexpected references left behind and can be hard to reason about when multiple Requests reference the same mutable Session.

 I don't think a hook is necessarily the best approach to accomplish what you're looking for. It sounds like you're already subclassing the Session or using a mixin to add your new attributes. You might consider continuing down that route and subclassing the `Request`s yourself. Otherwise, you may be better to look at having something like a Request manager to manage Request state/retries, or perhaps the retry functionality in urllib3.
