### ISSUE TITLE
kali linux mimtf installation error

### ISSUE THREAD

**Issue by dr55555** [psf/requests#5387]
Received response with content-encoding: gzip, but failed to decode it  error -3 while installing mimtf

**Comment by nateprewitt** [comment]
Hi @dr55555, there isn't enough information here for us to work with. It's not clear what Requests has to do with the installation of mimtf. If you can provide a full stack trace or a small reproduction sample that shows a defect in Requests that would be helpful.

For the time being I'm going to resolve the ticket since there aren't any actions we can take.
