### ISSUE TITLE
requests.get failed with AuthenticationRequired error but urllib.request.urlopen works

### ISSUE THREAD

**Issue by jiongjiongli** [psf/requests#5393]
Summary.
requests.get failed with AuthenticationRequired error but urllib.request.urlopen works.
The computer access google url with shadowsocks client.

```
>>> requests.__version__
'2.23.0'
>>>
>>> url = 'http://storage.googleapis.com/tfds-data'
>>>
>>> response = requests.get(url)
>>> response
<Response [401]>
>>> response.content
b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>"
>>>
>>> urllib.request.urlopen(url).msg
'OK'
```

## Expected Result
requests.get(url) works.

## Actual Result
```
>>> response
<Response [401]>
>>> response.content
b"<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>"
```
## Reproduction Steps
The computer access google url with shadowsocks client.

```python
import requests
import urllib.request
url = 'http://storage.googleapis.com/tfds-data'
response = requests.get(url) # It doesn't work.
response
response.content
urllib.request.urlopen(url).msg # It works.
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "19.3.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.23.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.24.3"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
Hi @jiongjiongli,

I'm unable to reproduce this issue with the code provided, I get identical responses across both Requests. Something you're sending in the first request is triggering an authentication challenge. I'd verify you're not providing credentials from a .netrc file or another mechanism. The easiest way to check is seeing if there's an `Authentication` header in your initial `request` object. You can access that off your response with `response.request`.

If that doesn't resolve the issue, I'd suggest opening a new question on Stackoverflow.com to continue debugging. This is a local configuration issue rather than a defect in Requests, so I don't believe this is the best place to track. I'm going to resolve for now.

**Comment by jiongjiongli** [comment]
@nateprewitt OK. Thanks a lot!
