### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))

### ISSUE THREAD

**Issue by victorb37** [psf/requests#5400]
**I am getting this error in return when running Twitterscraper on Python. 

This is the the code that was used:** 

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

from twitterscraper import query_tweets
import datetime as dt
import pandas as pd

begin_date = dt.date(2020, 2, 17)
end_date = dt.date(2020, 3, 20)

limit = 2000
lang = 'english'

tweets = query_tweets('coronavirus deaths', begindate = begin_date, enddate = end_date, limit = limit, lang = lang)

df = pd.DataFrame(t.__dict__ for t in tweets)

filt = df['text'].str.contains('coronavirus deaths')

df = df.loc[filt]

export_excel = df.to_excel (r'C:\Users\victo\Desktop\coronavirus.xlsx', index = None, header=True)

**How can I fix this issue?**

**Comment by nateprewitt** [comment]
Hi @victorb37,

This is due to either the web server you're hitting being unable to negotiate a proper TLS connection or potentially an issue with the version of OpenSSL you have installed on your machine.

Neither of these are issues directly with Requests though which is what we have this issue tracker reserved for. Your best bet will be to create a question on Stackoverflow.com with the `python-requests` tag to debug there. Thanks!
