### ISSUE TITLE
json parameter should transform booleans

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [psf/requests#5420]
Summary.
`json=` parameter should correctly transform booleans.

## Expected Result
Given this:

```
resp = req.post('https://example.com/endPoint',
  json={ "foo": false }
)
```
I'd expect this to work, and python to correctly transform `false` to `False`.

## Actual Result
Instead, I get `"foo": false, NameError: name 'false' is not defined`

This works:

```
resp = req.post('https://example.com/endPoint',
  json={ "foo": False }
)
```

And this works:

```
payload = json.loads("{ "foo": false }")
resp = req.post('https://example.com/endPoint',
  json=payload
)
```

Therefore this is an request for enhancement that the `requests` library handle this for us, so that it "just works".

**Comment by sigmavirus24** [comment]
The requests library can not change the actual syntax of Python

**Comment by ghost** [comment]
Yes, but you can include some rudimentary transformation inside the `post` method?

**Comment by sigmavirus24** [comment]
I don't think you understand what is happening here, @Dynatrace-Adam-Gardner .

Try just doing:

```py
json={ "foo": False }
```

You're binding a dictionary using Python's syntax to a name - `json`. With this you could then do

```py
requests.post(url, json=json)
```

Likewise you can pass that dictionary in as you are trying to but Python's lexer and syntax are inescapable inside the `(` and `)` because `requests` literally can neither change the lexer nor the syntax of the compiled Python binary.

There is absolutely nothing a library like Requests can do in this case.

If you want you can do:

```py
false = False
```

And thus you've done your own rudimentary transformation, but there is no pre-processing that Requests can do because it's executed after Python has lexed the code and is executing it. The `NameError` you're getting comes directly from Python.

**Comment by ghost** [comment]
You guessed correctly. I'm very very green with Python. Thanks for the info. I'll close this now :) ;)
