### ISSUE TITLE
Possible bug or incorrect usage (on my end)

### ISSUE THREAD

**Issue by liquidoshin** [psf/requests#5457]
Hi so I'm using your requests module and everything was working fine when I was using it with python2. However, now that I'm on Mac OS Catalina and there's only python3 I've had to revise my code a little and now I'm getting some errors. So I have a little bit of code as follows:
response = requests.get(resource,
                                    headers={
                                        "Authorization": "Basic " + base64.b64encode(
                                            self.username + ":" + self.passwd
                                        ),
                                        "Accept": datatype
                                    },
                                    proxies={"https": None,
                                             "http": None})

And when I run my script it gives me an error:
File "/Users/dwalker/Documents/workspace/jamfapi/jamfapi_src/jamfapi/jss/JSSRestIface.py", line 48, in jamfApiCall
    self.username + ":" + self.passwd
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

Now I had issues similar to this in another project when we converted from py2 to py3 and we resolved it by running .decode("utf-8") with the output object we were getting back from a command being run. However, I'm not sure if this is the same issue. Any ideas on what I'm doing wrong here or how I'm using requests incorrectly?

Thank you.

**Comment by thatcomputerguy0101** [comment]
In Python3, the default encoding for strings changed. I believe if you want a Python2 style string, you need to prefix it with b as in `b"Byte text"`. Your issue is probably related to the distinction between string objects and bytes objects. Using decode, you can convert from bytes to string, and encode will convert from string to bytes. The docs probably have better information, with [strings documented here](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str) and [bytes documented here](https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview).

**Comment by sigmavirus24** [comment]
This is your incorrect usage. Also you don't need t oencode that yourself since `auth=(self.username, self.passwd)` would do the trick. You could also use `requests.auth.BasicAuth`.

**Comment by liquidoshin** [comment]
sigmavirus24 so where would I use the auth=(self.username, self.passwd)? I'm a little confused.

**Comment by sigmavirus24** [comment]
First page of the docs demonstrates this https://requests.readthedocs.io/en/master/

**Comment by nateprewitt** [comment]
Resolving since this seems to be addressed. 

Direct link to [auth docs](https://requests.readthedocs.io/en/master/user/authentication/#basic-authentication) for future readers.
