### ISSUE TITLE
for non-english response, may add apparent_text for convenient

### ISSUE THREAD

**Issue by NewUserHa** [psf/requests#5470]
most non-English response has incorrect r.encoding so it need:
```
r.encoding = r.apparent_encoding
r.text
```

what about a new attribute like `r.apparent_text` or `r.text(chardect=True)`for the result?

Thanks!

**Comment by NewUserHa** [comment]
https://github.com/psf/requests/issues/5084
https://github.com/psf/requests/issues/2086

**Comment by sigmavirus24** [comment]
New features are not being added

**Comment by NewUserHa** [comment]
I have read that and I don't think this can count as a feature.

**Comment by sigmavirus24** [comment]
Adding new API surface area is a new feature. Further, if `r.encoding` is incorrect but `r.apparent_encoding` is correct that means the server is reporting the wrong thing and that's what the library is trying to use. In other words, there's a perfectly good work around here.

**Comment by nateprewitt** [comment]
Hi @NewUserHa,

sigmavirus24 is correct that we aren't adding any new features currently which this would fall under. If chardet is incorrectly detecting an encoding, I would suggest reaching out to the [library](https://github.com/chardet/chardet) to see if you can help identify the issue. Otherwise, setting the encoding when the server returns an incorrect response is the best option to get around this.
