### ISSUE TITLE
Read timeout errors are converted to connection errors by adapter

### ISSUE THREAD

**Issue by janheindejong** [psf/requests#5517]
When adding an adapter with a retry object to a session, read timeout errors are converted to connection errors. 

```python 
>>> s = requests.Session()
>>> s.get("http://whatever.com", timeout=(3.05, 0.001))
Timeout: HTTPConnectionPool(host='whatever.com', port=80): Read timed out. (read timeout=0.001)
>>> a = HTTPAdapter(max_retries=Retry(total=3))
>>> s.mount("http://", a) 
>>> s.get("http://whatever.com", timeout=(3.05, 0.001))
ConnectionError: HTTPConnectionPool(host='whatever.com', port=80): Max retries exceeded with url: / (Caused by ReadTimeoutError("HTTPConnectionPool(host='whatever.com', port=80): Read timed out. (read timeout=0.001)"))
```

Is this intentional? If so, what's the reasoning behind it? I'd like to catch these errors, but handle connection errors differently (e.g. warn the user to check his internet connection) from timeout errors (e.g. inform the user that the requested resource is possibly overloaded). Wouldn't it make more sense to raise the original error type once the max number of retries is exceeded?

**Comment by janheindejong** [comment]
Whoops... just saw this is a duplicate of #5430. From what I understood the consensus is that it would indeed be better to change this behavior, but for backwards compatibility it will not be done before a new major release of the package (i.e. 3.0).

Is there already a PR for this? I'd be happy to give it a go...

**Comment by jakermx** [comment]
Nope...if the socket is dropped because  your OS have  lower layer tcp keep alive disabled, your will get a Connection Timeout...because you are asking the server something but you are not being heard...

This work inLinux clients...there are the same for all OS


 
    **import socket
    from urllib3.connection import HTTPConnection
    HTTPConnection.default_socket_options = HTTPConnection.default_socket_options + [
        (socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
        ,(socket.SOL_TCP, socket.TCP_KEEPIDLE, 45)
        ,(socket.SOL_TCP, socket.TCP_KEEPINTVL, 10)
        ,(socket.SOL_TCP, socket.TCP_KEEPCNT, 6)
         ]**

    from requests import session
    self.session = session()

this way....when a HTTP Persistence Connecion is requested and no data is being transfered , the client will notify the server that stills up....they are Persistence , so the client needs to  keep online and waiting...if not, the server will drop the connection without advise.
