### ISSUE TITLE
Cannot jump to Japanese documentation

### ISSUE THREAD

**Issue by senbeiman** [psf/requests#5518]
The link to Japanese documentation is redirected to English one.

## Expected Result
As you know, there are translation links in the sidebar of [documentation page](https://requests.readthedocs.io/en/latest/), 
but I can't jump to the Japanese documentation page.
I expect to jump to [this page](https://requests-docs-ja.readthedocs.io/en/latest/)

## Actual Result
The link to Japanese translation page is redirected to the English page.

## Reproduction Steps
Just clicking the link of documentation

**Comment by arthtyagi** [comment]
i tried a few other links including https://requests.readthedocs.io/jp/latest/ and https://requests.readthedocs.io/zh_JP/latest/,
seems like it's just not ready yet.

**Comment by nateprewitt** [comment]
Hi @senbeiman, thank you for reaching out about this. The doc translations have all been owned by separate maintainers since their inception. The Japanese documentation is hosted [here](https://github.com/requests/requests-docs-jp) but appears to be almost 7 years out of date. I'm not sure if we have a current alternative unfortunately.
