### ISSUE TITLE
response.text is too slow

### ISSUE THREAD

**Issue by GoddessLuBoYan** [psf/requests#5523]
if response.content is too long(3MB) and there's no encoding, response.text will auto calculate the encoding, it takes me 15 seconds(33 for the debug mode)
so, what if we calculate the encoding only for content[0:1024]?
(if failed, we can add content[1024:2048] into the encoding-calculater and get the newest result)

**Comment by nickroeker** [comment]
`chardet` (the package which guesses the encoding) works better with the more data you give it. If you already need to _guess_ the encoding, you need to look at as much of the data as possible to guess more accurately. Guessing off the first 1kiB wouldn't be useful for a number of cases (e.g. if the response has a lot of ambiguous preamble), so it wouldn't be a good idea for the `requests` library to do this. It also doesn't "fail" per se - it may determine the wrong encoding due to insufficient data, but that won't necessarily throw an error.

You can set `reponse.encoding` yourself if you know it ahead of time. But if you truly need to make guesses and use the `chardet` functionality, then you do need to let it operate over the whole response for best results. In this case, you may want to monkey-patch `requests` with something like [cChardet](https://pypi.org/project/cchardet/) to speed it up.

**Comment by GoddessLuBoYan** [comment]
> `chardet` (the package which guesses the encoding) works better with the more data you give it. If you already need to _guess_ the encoding, you need to look at as much of the data as possible to guess more accurately. Guessing off the first 1kiB wouldn't be useful for a number of cases (e.g. if the response has a lot of ambiguous preamble), so it wouldn't be a good idea for the `requests` library to do this. It also doesn't "fail" per se - it may determine the wrong encoding due to insufficient data, but that won't necessarily throw an error.
> 
> You can set `reponse.encoding` yourself if you know it ahead of time. But if you truly need to make guesses and use the `chardet` functionality, then you do need to let it operate over the whole response for best results. In this case, you may want to monkey-patch `requests` with something like [cChardet](https://pypi.org/project/cchardet/) to speed it up.

yeah, I did like this. It's easy

**Comment by batterseapower** [comment]
You can use `chardet` incrementally (https://chardet.readthedocs.io/en/latest/usage.html#advanced-usage). Maybe feeding the document in piece by piece (and stopping as soon as chardet is confident about the encoding) would solve the problem?

**Comment by verhovsky** [comment]
Another suggestion for replacing `chardet` is https://github.com/google/compact_enc_det . It's what Google Chrome uses to detect the encoding. It's written in C++ and I'm not aware of any Python bindings for it though, so you'd have to write them yourself.

**Comment by jakermx** [comment]
Read the HTTP headers for content lenght , use chunks retrival iterations  with AJAX or DOM... as action

Well, you can use it just if you know how the data is being encasulated...

**Comment by GoddessLuBoYan** [comment]
Oh, I forget to close this! Thanks for everyone.
