### ISSUE TITLE
Avoid reading unlimited body of the redirect

### ISSUE THREAD

**Issue by Sindbag** [psf/requests#5529]
https://github.com/psf/requests/blob/1b417634721ec377abb7f17bc1f215e07202c2f7/requests/sessions.py#L160:L164
Here socket is read till the end, but in case of unlimited or extremely huge body the process is stuck.
Solution I can assume - drop connection in case of extremely huge body (unlimited by default), as redirect meaning is kept inside headers, unlimited body seems to be a vulnerability.

**Comment by sigmavirus24** [comment]
Not reading the entire body is also a vulnerability and was a deliberate choice. There's no way to close the socket from Python without draining it or otherwise causing a significant memory leak. So on one hand, you read a lot of data off the socket, on the other your program OOMs

**Comment by nateprewitt** [comment]
Hi @Sindbag, sigmavirus24 is correct that we have to read everything on the socket. Choosing an arbitrary threshold for what constitutes "unlimited" becomes difficult because many users use Requests for long lived responses. There are a handful of libraries out there that will allow you to set a hard timeout around your request. That is probably the best option for defending against this kind of issue.
