### ISSUE TITLE
Multi post request in Session doesn't use single connection

### ISSUE THREAD

**Issue by chenhd** [psf/requests#5604]
I use session object to make the request, but I see the connection will be close after the request, because I see the client sent the tcp-FIN flag to the server by wireshark.

-------------
python 3.7.7
requests 2.24.0
win10

**Comment by sigmavirus24** [comment]
We send `Connection: keep-alive` but we can't control the server. This isn't a requests bug and you've provided none of the required informatoin

**Comment by chenhd** [comment]
I found a information, open the logging, it print something:

DEBUG:urllib3.connectionpool:Resetting dropped connection: (this is a ip)

in two same post request. 
@sigmavirus24

**Comment by sigmavirus24** [comment]
I'll reiterate one last time, @chenhd - this is not a requests bug.

Read up on the TCP state machine and how the fact that the server itself is closing the socket. We can't reuse a closed connection.

I've locked this because this is resolved and you've not been respectful of the project's time by neither filling out the template nor understanding that this isn't a bug and continuing to comment here
