### ISSUE TITLE
requests.post() does not work until reset modem

### ISSUE THREAD

**Issue by kaloomte** [psf/requests#5650]
Hi everyone
I have an interesting problem. When i run my basic script with raspberry pi i get response but after a couple post,  my codes do not work anymore until i reset the modem or reset my phone if i connect with my phone network.

```
import requests
import json
import time
url = '...'


myobj = {"status":1,"makina_id":1,"ambalaj":{"boyut":0.5,"cins":"plastic"},"doluluk":50,"error":0}
x = requests.post(url,json.dumps(myobj))
print(x)
print(myobj)
```

****Output** is**

```
<Response [200]>

{'status': 1, 'makina_id': 1, 'ambalaj': {'boyut': 0.5, 'cins': 'plastic'}, 'doluluk': 50, 'error': 0}
```
when the problem occuring, there is not any output, any error or warnings.

I could not find what is the problem. Thank you for your helps.

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. This is likely related to your network or timeout settings. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
