### ISSUE TITLE
Uri and request from other language

### ISSUE THREAD

**Issue by GeorgeTheodorak** [psf/requests#5687]
Hello.
I am currently tring to request a page using .get 
my problem is that when i use specific chars become %something but i what be completed like this
"https://test:search?keyphrase=ΤεστΕδωΕχειΕλληνικα"
but the requests changes those greek chars before sending it .
Is there any way to fix this.
Thanks in advance.

**Comment by sethmlarson** [comment]
Requests is doing the right thing by percent-encoding that phrase.

Browsers have this exact behavior because it's complying with standards (see RFC 3986). This is what the request looks like from Firefox:

```
https://test:search?keyphrase=%CE%A4%CE%B5%CF%83%CF%84%CE%95%CE%B4%CF%89%CE%95%CF%87%CE%B5%CE%B9%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%B1
```

The server should be following this standard as well, otherwise many clients (Requests, Firefox, Chrome, etc) will not work.
