### ISSUE TITLE
Gzip decompression corrupts file

### ISSUE THREAD

**Issue by eloparco** [psf/requests#5803]
## Summary
I want to download a gzip file (`https://iptoasn.com/data/ip2asn-v4.tsv.gz`) and save it locally already decompressed.
According to the [docs](https://docs.python-requests.org/en/master/user/quickstart/#raw-response-content), downloading a compressed file should automatically decompress it. 

## Expected Result

The `ip2asn-v4.tsv` file correctly decompressed.

## Actual Result

The `ip2asn-v4.tsv` generated is corrupted. Below the content after opening it with excel:

![image](https://user-images.githubusercontent.com/37975547/116474115-60e38f00-a878-11eb-8a1b-816ff9b89e54.png)

## Reproduction Steps
This is the minimal code snippet to reproduce my use case:
```python
import requests
r = requests.get('https://iptoasn.com/data/ip2asn-v4.tsv.gz', stream=True)
with open('ip2asn-v4.tsv', 'wb') as fd:
    for chunk in r.iter_content(chunk_size=None):
    fd.write(chunk)
```

**Comment by sethmlarson** [comment]
If you look at the headers on your response you'll see that there is no `Content-Encoding: gzip` which you seem to be expecting. Even if you forcibly send `Accept-Encoding: gzip` the URL doesn't reply with a `Content-Encoding`, so Requests won't automatically decode the gzipped file because the endpoint hasn't declared it (and it wouldn't make much sense for the endpoint to do so, it's already gzipped and gzipping again will make the file even larger!)

Instead you need to gzip-decompress the file contents yourself, I recommend `gzip.decompress()` or `gzip.GzipFile` for streaming.

In the future, this isn't the place for asking questions about how to use Requests, this is for tracking defects in Requests (which this is not). Try Stack Overflow next time.

**Comment by eloparco** [comment]
You're right, thanks for the answer :)
