### ISSUE TITLE
Timeline for fixing #5710?

### ISSUE THREAD

**Issue by dfrankow** [psf/requests#5824]
I see https://github.com/psf/requests/issues/5710 says #5711 will fix an issue with using an old idna. Looks like the last movement there was Jan 20, now about 4 months ago.

Can you offer any guidance on when #5710 will be fixed?

Like others, this is blocking some of my development. In particular, I wish to try https://github.com/karolyi/py3-validate-email, which requires `idna~=3.0`, incompatible with the current requests requirements.

**Comment by nateprewitt** [comment]
Hi @dfrankow,

As the last comments in both of those issues state (https://github.com/psf/requests/issues/5710#issuecomment-830211618) (https://github.com/psf/requests/pull/5711#issuecomment-764017260), this is likely to be included in the next release of Requests. The change is unfortunately breaking for a subset of users which is the reason it hasn't been merged yet.

We are pending outcomes on some other open PRs before creating the next release so there is no hard timeline. In the future, please keep discussions to the relevant issue instead of creating new ones. It creates unnecessary noise for those watching this repo and makes it difficult to track conversations on the topic. Thanks!

**Comment by dfrankow** [comment]
Thanks for your response.
