### ISSUE TITLE
JSON parameter string in requests.post

### ISSUE THREAD

**Issue by L-lei** [psf/requests#5830]
Shouldn't the content of JSON parameters be judged by type? isinstance(json_content,dict)
res = requests.post(url=url,json='{"a":1}'),In this way, the receiver needs to deserialize JSON twice to get the data

**Comment by sigmavirus24** [comment]
No, it's clearly documented as something that _will_ be JSON serialized with a JSON library. That means what you pass in will be passed to a serializer. Some people may want to pass a string and have that properly serialized. What would you expect to happen if we you did `json="Some text"`? That should be `"\"Some text\""` otherwise a server will never deserialize it properly.
