### ISSUE TITLE
proxy with custom hostname on proxy (possible bug ?)

### ISSUE THREAD

**Issue by flapili** [psf/requests#5879]
Hi, I'm running zaproxy behind an nginx to perform some audit on our customer website,
infortunally I have few issues with requests proxying.

```
curl -x https://xxx.xxx.xxx -L http://zap
```

```
<head>
<title>ZAP API UI</title>
</head>
<body> ... </body>

```

but with requests (not exactly the same request):

```
req = requests.post(
    "http://zap/JSON/spider/view/scans",
    proxies={"https": settings.owasp_proxy_url},
    data={"apikey": settings.owasp_api_key.get_secret_value()},
)
```

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='zap', port=80): Max retries exceeded with url: /JSON/spider/view/scans (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb1f84c2730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

Python: 3.9
requests: 2.25.1

Best regards

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

`nodename nor servname provided, or not known` means we could not resolve the name via DNS for `zap`. Requests delegates to the standard library (which delegates to the operating system) to resolve DNS. We do not use the proxy to find DNS servers so you need to ensure that your system is configured appropriately.
