### ISSUE TITLE
DOC,BUG: 404: Spanish translation links require .html

### ISSUE THREAD

**Issue by westurner** [psf/requests#5902]
At least the Spanish translation links in the RTD widget are 404'ing.

1. https://docs.python-requests.org/en/master/user/quickstart/
2. Click 'es' under Languages in the RTD widget
3. 404

From @astrojuanlu 
https://twitter.com/juanluisback/status/1425742688595464200 :

> It is indeed available, but notice the .html at the end of the URL https://docs.python-requests.org/es/latest/user/quickstart.html
> 
> Looks like the configuration of the projects is not uniform. Would you open an issue on the requests tracker? Feel free to ping me, happy to help!

**Comment by astrojuanlu** [comment]
Thanks for the ping @westurner!

I see that https://github.com/requests/requests-docs-es has not received any attention in 5 years, not sure about the other translations. In any case, even if those docs are very outdated, I wonder if some config changes on the RTD or Sphinx side can at least amend the most obvious issues, like this one.

**Comment by sigmavirus24** [comment]
> I wonder if some config changes on the RTD or Sphinx side can at least amend the most obvious issues, like this one.

I believe the configuration is literally in the sphinx conf file in that translation repo which I do not have access to merge things to. I don't believe RTD can just fix this

**Comment by nateprewitt** [comment]
What's interesting here is the pages are actually live. You can see that the prefixed domains in the sidebar work fine (i.e. https://de.python-requests.org redirects to https://docs.python-requests.org/de/latest/).

It looks like the primary docs for Requests are using `/en/master` instead of `/en/latest`. This is breaking the language navigator because the translations only exist at `/<language code>/latest`. If you navigate [here](https://docs.python-requests.org/en/latest/), the widget works correctly. This is almost certainly a bad configuration in [RTD](https://readthedocs.org/projects/requests/).

I don't think any maintainers have had access to that account since at least 2018, so we'll need @ewdurbin or @kennethreitz to help with this.

**Comment by nateprewitt** [comment]
Alright, it looks like we’ve got the pointers sorted. https://docs.python-requests.org should now point to “latest” renabling the correct behavior in the nav widget.

Thanks again for the report!

**Comment by westurner** [comment]
Thanks!
