### ISSUE TITLE
How pass urllib3 assert_hostname in Requests Adapter?

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#5931]
Hello,

What do I need to customize to prevent host name checking?  I am assuming it's the HTTPSConnectionPool's assert_hostname=False bit of code.

Since I cannot find any documentation on this, I was wondering if the developers can help me decide where to implement this customization?  

My guess was by inheriting from `HTTPAdapter` then modifying the `__init__()` to allow a user to pass in the assert_hostname=True/False.

Once that is done, would I overload the `verify_cert` method?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here. Please be sure to include what you've tried, what you saw as a result, and what you were expecting.

**Comment by achapkowski** [comment]
@sigmavirus24 I did try stack exchange, posted code and got down voted.  I came here for help, because I can't find the documentation on where/how this should be done. 

https://stackoverflow.com/questions/69102923/python-requests-setting-assert-hostname-to-false
