### ISSUE TITLE
Why isn't requests_ntlm included in requests library?

### ISSUE THREAD

**Issue by CaledoniaProject** [psf/requests#6046]
I'm wondering if there's any reason that requests won't include https://pypi.org/project/requests_ntlm/ in the official repo?

**Comment by nateprewitt** [comment]
Hi @CaledoniaProject, Requests specifically has opt-in functionality like oauth and ntlm created in separate repos because they're not part of the library's core http functionality. You'll also find other tools in the requests toolbelt.

The primary reason is to avoid unnecessary bloat and overhead for non-critical functionality.

**Comment by CaledoniaProject** [comment]
Understood, thanks.
