### ISSUE TITLE
How to handle this issue ? - [Errno 110] Connection timed out') - Max retries exceeded with url - HTTPSConnectionPool(host=..., port=443

### ISSUE THREAD

**Issue by juandavidbriceno** [psf/requests#6132]
Good evening,

After having searched in stackoverflow for answers to my question, I was not able to find any solution. Currently I'm trying to use the request package to retrieve environmental data from a gobernment site by using url get requests. When I do the request through postman it works, but surprisingly with my python (jupyter notebook) scripts it does not.

It was working perfectly before but after starting using sessions ( s = requests.Session()) then it began to produce problems.

This is the code:
s = requests.Session()
my_uri = '.....'
r_metadata= s.get(my_uri, headers={'Authorization': 'ApiToken ..............'})
print(r_metadata.status_code)

---------------------------------------------------------------------------------------------------------
This is the error encounter:
HTTPSConnectionPool(host='.....', port=443): Max retries exceeded with url: ....... (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8256a0310>: Failed to establish a new connection: [Errno 110] Connection timed out')

------------------------------------------------------------------------------------
What I think is that these persistent session from requests are still alive, and for that reason the third party server from which I'm trying to get the data, dont allow me to enter anymore and take the information(Max retries exceeded with url:).

Would you mind giving me a suggestion or solution?.

Cordially,

Juan David Briceno Guerrero

**Comment by nateprewitt** [comment]
Hi @juandavidbriceno, what you're observing is likely intentional behavior from the website to prevent web scraping. Requests often ends up on fingerprinting lists which CDNs or websites can use to prevent programmatic access. The service is refusing to respond within the default connection timeout, which implies it's just rejecting the connection.

You can try extending the timeout which there is guidance for in the docs. Otherwise, I don't believe we'll be able to help because this is a server side issue.
