### ISSUE TITLE
No module named 'urllib3.exceptions'

### ISSUE THREAD

**Issue by doraspocket** [psf/requests#6143]
from .exceptions import RequestsDependencyWarning
  File "/Users/ericli/venvs/venv3.10.3/lib/python3.10/site-packages/requests/exceptions.py", line 9, in <module>
    from urllib3.exceptions import HTTPError as BaseHTTPError
ModuleNotFoundError: No module named 'urllib3.exceptions'; 'urllib3' is not a package

**Comment by doraspocket** [comment]
Hi,
I'm using venv, and has already installed requests, but when I was trying to import requests, It always got the error,

No module named 'urllib3.exceptions'

(venv3.10.3) ➜  pyspider-urllib git:(main) ✗ pip list
Package            Version
------------------ -----------
certifi            2022.5.18.1
charset-normalizer 2.0.12
idna               3.3
pip                22.0.4
requests           2.27.1
setuptools         58.1.0
urllib3            1.26.9

**Comment by MichaelFriedel** [comment]
Hello @doraspocket, did you possibly mean to import the Requests Dependency Warning from Requests instead of urllib3? If this is the case, use the import statement below:

`from requests.exceptions import RequestsDependencyWarning`
 
Both urllib3 and requests have a file called exceptions.py so by referring to it as ".exceptions", I suspect your import statement tried to pull from urllib3 instead.

**Comment by nateprewitt** [comment]
Hi @doraspocket, I'd recommend verifying you don't have a file named `urllib3.py` or another relative directory named `urllib3` in your path for your project. This is a configuration or pathing issue on your machine/venv that unfortunately we won't be able to assist with on this issue tracker. We'd recommend posting on [StackOverflow](https://stackoverflow.com/) for further assistance.
