### ISSUE TITLE
timeout parameter not applied to initial connection

### ISSUE THREAD

**Issue by chatumao** [psf/requests#6145]
If specifying the timeout parameter to requests.get(), an exception is raised after the specified timeout. If the code is executed without an internet connection, an exception is raised immediately. Python is at 3.10.

## Expected Result

It feels like the timeout should apply to this scenario as well.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by nateprewitt** [comment]
Hi @chatumao, the timeout is for reads and connections. This isn't a wall clock, as specified in the docs, it's for each operation. If we cannot connect (and therefore cannot read), there's nothing for the timeout to apply to which is why we fail immediately.

I don't believe we intend to change this behavior at this time.

**Comment by chatumao** [comment]
Ok, thanks for clearing that up.
