### ISSUE TITLE
Error Partially initialized module 'requests' has no attribute 'post'"

### ISSUE THREAD

**Issue by werowe** [psf/requests#6196]
If you have a file named token.py in your path you get the error:

**Error Partially initialized module 'requests' has no attribute 'post'"**

 That is the case with Python 3.8.9 and Requests Version: 2.28.1 on Mac OS 12.4.

**Comment by sigmavirus24** [comment]
I don't believe we import anything directly that would cause that so it's likely an issue with a dependency it the standard libraries we rely on. Therefore, it's not a bug we can fix. Rename your file to not conflict with what (based on my memory, since I'm on my phone) is a standard library package.

Also you ignored the issue template
