### ISSUE TITLE
Python Requests Libarary Removes some Characters in URL when Sending Request

### ISSUE THREAD

**Issue by nxenon** [psf/requests#6210]
Python **requests** library changes URL in some situations.
it removes some parameters
for example
`
url = "https://www.example.com/test?"
`
it removes `?` in the request when I see it in Burp proxy
it changes to 
`https://www.example.com/test`
because I'm pentesting web applications I need to send for example quotation mark too and other things which will be removed by library automatically.
I need following path:
![image](https://user-images.githubusercontent.com/61124903/182108804-e9811743-2ba4-41d3-8266-9e6d97998e4a.png)
after ? must be empty

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

In the future, please search **closed and** open issues before creating new ones that are duplicates.
