### ISSUE TITLE
requests.patch does not work, REST app does

### ISSUE THREAD

**Issue by uncommonephemera** [psf/requests#6308]
Hello. I am attempting to update records through the Directus API with requests.patch.

Given the following code:

```
#!/usr/local/bin/python3

import requests

id = 1000
api_url_root = "[redacted]" 
api_access_token = "[redacted]"

api_url = api_url_root + "/items/filmstrips/" + str(id) + "?access_token=" + api_access_token

response = requests.patch(api_url, data={'problem':True}) 
```

The Directus server responds 200, and the Directus logs state:

```
[18:52:03] TRACE (4106 on uncommonephemera): [1.144ms] update `filmstrips` set `date_updated` = ?, `user_updated` = ? where `id` in (?) [Wed Dec 14 2022 23:52:03 GMT-0500 (Eastern Standard Time), [userid UUID redacted], 1000]
```

...which does not indicate the field "problem" is altered. Going in to Directus shows the field is not set to True.

I downloaded RapidAPI and sent the same request as shown in the screenshot:

[https://imgur.com/a/1IesDhD](https://imgur.com/a/1IesDhD)

The Directus logs show:

```
[19:03:17] TRACE (4106 on uncommonephemera): [0.876ms] update `filmstrips` set `problem` = ?, `date_updated` = ?, `user_updated` = ? where `id` in (?) [true, Thu Dec 15 2022 00:03:17 GMT-0500 (Eastern Standard Time), [userid UUID redacted], 1000]
```

....which shows that the field "problem" is updated. Upon going into Directus, the field is set to True.

Everything I've been able to read or search for about requests says this is how I'm supposed to do it. I've been at this all afternoon, trying different things, nothing works. Using version 2.28.1. How can I make this work?

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here. 

Please also closely read the documentation about inspecting the data you've sent in a request, how to send JSON data, and how to send urlencoded data as I expect these will help you find your solution.

Also note that screenshots are useless for offering help as many people rely on screen readers and further they aren't searchable to help others encountering similar issues

**Comment by uncommonephemera** [comment]
I'd say if all the documentation available says to do it this way, and it doesn't work, that's a defect.

I'm not entirely sure how to describe what I've done in a GUI app that wouldn't generate a thousand questions about what I inadvertently left out of the description or imply I didn't do something I should have.

I tried json.dumps(payload), json=payload, and adding the Content-Type header, none of that made any difference.

Either way, it sounds like everyone here is certain the library is problem-free (talk about needing a screen reader), so I'll be on my way. HTTP for humans, my ass
