### ISSUE TITLE
Duplicate #6261

### ISSUE THREAD

**Issue by thetechnodino** [psf/requests#6315]
Duplicate #6261

Nate: Sorry i posted duplicate.  Probably posted in the wrong place. Newbie and my first post on the forum.
You closed #6314 as duplicate of #6261. I was not making a feature request but seeking help.  
I was hoping to get help in solving the issue I am experiencing with RequestsDependencyWarning error messages.

**Comment by nateprewitt** [comment]
Hi @thetechnodino, your last issue was closed because the warning you're encountering is discussed in the issue linked. For the time being you can downgrade to `charset_normalizer<3.0` if you're trying to get rid of the warning.

For future reference, please follow the instructions provided when you opened this issue. Thanks!

> Please refer to our [Stack Overflow tag](https://stackoverflow.com/questions/tagged/python-requests) for guidance.
