### ISSUE TITLE
I get confused using python documentation HELP

### ISSUE THREAD

**Issue by abhijit420kb** [psf/requests#6358]
for an example:
https://docs.python-requests.org/en/latest/api/#requests.cookies.RequestsCookieJar.set
`set(name, value, **kwargs)`
`Dict-like set() that also supports optional domain and path args in order to resolve naming collisions from using one cookie jar over multiple domains.`

But where I found `**kwargs` information's like what other arguments its take :-(
I mean about these arguments domain, path, expires, max_age, secure, httponly

All other functions are same as like this, I got total confused what to pass as parameters.

I am sorry for NOOB like question. but I am really straggle with it a lot.

in php.net they are describe all parameters properly. Where I found all parameters are hidden with `**kwargs`.

Thank you

**Comment by nateprewitt** [comment]
Hi @abhijit420kb,

This is specified at the top of the class:

```
Compatibility class; is a cookielib.CookieJar, but exposes a dict interface.
```

You can find the parameters supported by default in the constructor for Python's [Cookie](https://github.com/python/cpython/blob/3.11/Lib/http/cookiejar.py#L743-L801). This may vary depending on Python version/underlying CookieJar implementation which is why this information is defined to be optional `**kwargs`.
