### ISSUE TITLE
cannot import name 'DEFAULT_CIPHERS'

### ISSUE THREAD

**Issue by rasperin** [psf/requests#6438]
With the release of requests==2.3.0 it looks like it's pulling down urllib3==2.0.1, when trying to import requests on an aws lambda (python 3.9  manylinux_2_24_x86_64) I am getting:

[ERROR] Runtime.ImportModuleError: Unable to import module 'myapp': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/opt/python/urllib3/util/ssl_.py)

If it at all is important, requests is stored in a lambda layer.

## Reproduction Steps

Create a python3.9 AWS lambda:
```
import boto3
import requests

def lambda_handler(event, context):
    print(event)
    return None
```

Create a folder commonlib/python
Create packages in it
```
requests==2.3.0
```

pip install --quiet --upgrade -r commonlibs/python/packages -t commonlibs/python --only-binary=:all: --platform manylinux_2_24_x86_64

zip it up add it as a layer to aws
attach the layer to your lambda 
test the lambda
[ERROR] Runtime.ImportModuleError: Unable to import module 'myapp': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/opt/python/urllib3/util/ssl_.py)

## System Information

python version: 3.9
os: amazon linux 2 manylinux_2_24_x86_64

**Comment by nateprewitt** [comment]
Hi @rasperin,

This isn't an issue with Requests, but with the version of botocore (A dependency of boto3 which currently doesn't explicitly support urllib3 2.0) being used. It looks like you've installed incompatible dependencies in your Lambda which is leading to the error you're seeing.

This was already fixed in the latest release of Botocore with https://github.com/boto/botocore/pull/2924, so you can either upgrade boto3 or provide an older version of urllib3 in your package.

**Comment by rasperin** [comment]
Confirmed, sorry about that.

**Comment by nateprewitt** [comment]
No worries! Glad you got it sorted. I'll go ahead and resolve this then.
