### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by JamesAegina** [psf/requests#6510]
Hi all, getting this error when trying to run all scripts. Any ideas on how to fix would be greatly appreciated.

many thanks

TypeError: __init__() got an unexpected keyword argument 'strict'

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com/) for general usage questions instead and only report defects here.

For your Stackoverflow issue, you'll want to include the full stacktrace because there isn't enough information here. You may want to look at your version of urllib3 and any adapters your code may have interacting with it.
