### ISSUE TITLE
Unable to import requests - No module named `http.client`

### ISSUE THREAD

**Issue by mse63** [psf/requests#6511]
I am unable to import the requests library. I get a ModuleNotFoundError with `No module named 'http.client'

## Expected Result

Running `import requests` should not throw an error.

## Actual Result

Running `import requests` throws an error:
```
Traceback (most recent call last):
  File "/home/mahmoud/requests_test.py", line 1, in <module>
    import requests
  File "/home/mahmoud/.local/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/mahmoud/.local/lib/python3.10/site-packages/urllib3/__init__.py", line 11, in <module>
    from . import exceptions
  File "/home/mahmoud/.local/lib/python3.10/site-packages/urllib3/exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "/home/mahmoud/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/home/mahmoud/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/home/mahmoud/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'http.client'
```

## Reproduction Steps

```python
import requests
```
Obviously, not everyone is running into this issue. I'm not sure what's special about my system that would cause this.  I haven't done anything special or out of the ordinary with my server setup or python installation. Everything was working fine up until a few days ago when this issue just appeared unexpectedly for no apparent reason.

## System Information

Ubuntu Server 22.04, python3 version 3.10.12

**Comment by nateprewitt** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com/) for general usage questions instead and only report defects here.

```
ModuleNotFoundError: No module named 'http.client'
```
From this specific error, it seems you may have something shadowing the `http` namespace. You may have a file called `http.py` in your project. The [`http`](https://docs.python.org/3/library/http.html) and [`http.client`](https://docs.python.org/3/library/http.client.html#module-http.client) modules are available in all version of Python 3 we support in Requests.

**Comment by mse63** [comment]
I do not have anything shadowing the http namespace. I have no files named http.py or anything like that.

I can run `import http` then `dir(http)` yields `['HTTPStatus', 'IntEnum', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`

However, running `import http.client` yields the `ModuleNotFoundError`
