### ISSUE TITLE
Why encoding hard coding to "ISO-8859-1"

### ISSUE THREAD

**Issue by lizhaode** [psf/requests#6528]
## Expected Result
UTF-8 is better

## Actual Result
ISO-8859-1

## Reproduction Steps

I wanna download subtitle content, here is the code
```python
import requests
requests.get('https://events-delivery.apple.com/1008yunfyueoofvvgxpjmmvcblgnjsel/vod_main_bTVAkbqTcJuRovcmMRYungakLuiQyTWT/cc/zh/zh_0.webvtt',
                    headers={
                        'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
                        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',}.text
```
I found response.text is garble
through read code, found this snippet in "utils.py" on "def get_encoding_from_headers(headers)"
```python
    if "text" in content_type:
        return "ISO-8859-1"
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.4"
  },
  "platform": {
    "release": "21.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.31.0"
  },
  "system_ssl": {
    "version": "30100020"
  },
  "urllib3": {
    "version": "2.0.2"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by sigmavirus24** [comment]
You need to look at the response headers. The response is not providing an explicit `charset` otherwise we'd exit with this condition: https://github.com/psf/requests/blob/881281250f74549f560408e5546d95a8cd73ce28/src/requests/utils.py#L548

UTF-8 has increasingly become the "default" for newer sites, but Requests has to handle all content old and new. The easiest thing for any newer site to do is to properly specify it's `charset` because that's been supported since HTTP/1.0 if I remember correctly. 

Since your site is not specifying an encoding explicitly, Requests uses the next most common encoding if it can predict that the content is either `text/plain` or `text/html`. After that it'll use an external library to guess. You can always override the encoding yourself if you know what you care to use.

In the future, please search **closed and** open issues before creating new ones that are duplicates. There are **many** past issues discussing exactly tihs.
