### ISSUE TITLE
How to use multiple redundant hosts

### ISSUE THREAD

**Issue by andy-maier** [psf/requests#6615]
I would like to understand whether (and how) it is possible to configure requests to target multiple redundant hosts and to use one of them that is reachable.

Following the guideline to post such help requests in SO, I asked that in https://stackoverflow.com/q/76218020/1424462, and got a response there which so far I did not get to work. So I wanted to ask the maintainers directly.

**Comment by sigmavirus24** [comment]
@andy-maier looking at your StackOverflow question you're saying you don't want to use things that are the standard for achieving this. You don't want to use a load balancer because you don't want a single address (which doesn't make a great deal of sense) but fine. Is there a reason you're not leveraging DNS on your internal network? That would allow you to specify `hmc-service` as a DNS name which resolves to `N` addresses. `urllib3` would then retry those until they find one that works. There's countless StackOverflow questions around using dnsmasq and other free software to do exactly this.

In short, none of this is what one would expect of a typical HTTP client library providing the level of interface we provide. And urllib3 isn't exactly the right place for this either. If you want something like this, your issue in the client library is probably the best place because whatever logic you think is "right" here probably isn't right for a large enough percentage of requests or urllib3 users.

---

Put another way, many things operate in a fashion you're describing - databases with redundant servers as one example. In those cases the client libraries for those things do not rely on the underlying TCP libraries to allow users to specify how to connect/what redundant addresses are they either:

* Specify it at the client level (e.g., tell the library you want it to behave a [certain way](https://redis-py.readthedocs.io/en/stable/clustering.html) and either tell it the redundant addresses or have the remote service tell you how to find them)
* Specify it another way outside of the library's control (e.g., DNS; if you're on an IaaS that supports IP swapping, have a healthcheck that dynamically swaps the IP address of the thing you're trying to connect to over to one of the healthy redundant hosts; etc.).

---

Finally, the answer you received will not work likely because it looks like an AI hallucination to me and the person answering likely doesn't understand what is happening. SOCKS is a proxy protocol that is almost certainly completely unrelated to what you were asking so you don't need that at all. In fact, I'm 99% certain that's an LLM hallucination because the [SOCKS Proxy Manager](https://urllib3.readthedocs.io/en/stable/reference/contrib/socks.html#urllib3.contrib.socks.SOCKSProxyManager) does not have any [`resolver` attribute whatsoever](https://github.com/urllib3/urllib3/blob/main/src/urllib3/contrib/socks.py#L175) and neither does the class it inherits from.
