### ISSUE TITLE
Requests roadmap 

### ISSUE THREAD

**Issue by achapkowski** [psf/requests#6704]
Since the PSF took over management of 'requests' I am wondering what the road map is for this library?  Is it posted anywhere?  Is v3 totally dead?  Is the package just in maintenance mode? 

I know a few years ago things were very chaotic, but being removed from those bad times, where is the package going?

**Comment by sigmavirus24** [comment]
It's still just Nate and me. There isn't really any more time we can commit to the project than we already do. V3 as described to raise lots of money that didn't actually end up benefitting the project is still something desirable but will never be called V3 as none of those goals are recoverable from that website. So if we ever do have enough time to spend in a larger overhaul it will likely be named something else entirely.

**Comment by nateprewitt** [comment]
The project hasn't had any notable form of roadmap since the early releases of Requests 2.x. Almost all work on Requests 3.x stopped in 2017, so that's not a recent development. I think urllib3 2.0 has laid a path for a more gradual shift on improvements/minor breakages that we may be able to follow but there aren't any immediate plans as Ian noted. Requests is considered largely feature complete for its original purpose.

We'll continue to release bugfixes and general maintenance changes as we have, and if there is a point we have something that makes sense to add, we may consider it. Adding features for the sake of features though has never been a goal for Requests, so that's unlikely to change.

**Comment by achapkowski** [comment]
Is the PSF funding the project in anyway? Or just hosting it?

**Comment by sigmavirus24** [comment]
Neither Nate nor I can accept any funding due to our employers

**Comment by achapkowski** [comment]
Thank you, I appreciate both your work.
