### ISSUE TITLE
Lack of respect for questions and support requests

### ISSUE THREAD

**Issue by rfc-st** [psf/requests#6833]
Sincerely, I don't know what is the objective of those responsible for https://github.com/psf/requests, if they don't know how to kill this project, if they are bored or if they are simply busier with other things.

I have been observing your behavior for some time now, and it worries me:

.- Don't you have time to develop this library?: **perfect**.
.- Don't you want to continue to be responsible for it?: **perfect**.
.- Don't you know how to respond to support requests?: **perfect**.

But don't automatically refer support requests or problems to https://stackoverflow.com/: one of the most aggressive and rude sites when faced with support questions, especially from those who are just starting to program.

You should rethink, seriously, what to do with https://github.com/psf/requests: it is **far** behind other libraries that provide current functionalities, it is **far** behind for commits that really provide usefulness (you have been *months* without contributing anything useful to this library).

If you are tired, **perfect**: say it widely. And allow others to **continue** the work: people with enthusiasm and time to maintain and improve this library as it deserves.

Because our time is also **important**: don't give an image of an updated, friendly and supported library; because that's not the reality I see.

And this is said by someone who has recognized all your work: but sometimes it is **wise** to know when to give way to other people. And I maintain, on github, a project infinitely smaller than yours, but the moment I lose the illusion, the desire, the smile, to respond to every PR, every Issue, every suggestion, at that moment I will **hang up the gloves**, allowing wiser people to continue the path.

Regards,

**Comment by nateprewitt** [comment]
Hi @rfc-st,

This seems like more of an airing of grievances than actionable feedback but I'll try to address your points as concisely as we can.

Requests has triaged support questions through StackOverflow for a decade. We've had success with that because it provides a dedicated, more visible, space for your average developer. GitHub issues have proven less helpful because new users often ignore closed issues. While it might not be your preference, please understand your opinion isn't necessarily representative of all users of this library.

> it is far behind other libraries that provide current functionalities, it is far behind for commits that really provide usefulness (you have been months without contributing anything useful to this library).

Requests has had a largely stable feature set for the last ~10 years and it's been [documented](https://requests.readthedocs.io/en/latest/dev/contributing/#feature-requests) as being under feature freeze since 2.0. Both the HTTP and Python landscape has changed significantly in that time, and if there are other tools that better meet your needs, we'd encourage you to use them. Active feature development is not directly tied to the support of a library. Requests fits a fairly straight forward use case and we don't have immediate plans to change that.

> If you are tired, perfect: say it widely. And allow others to continue the work: people with enthusiasm and time to maintain and improve this library as it deserves.

I think we all agree there are opportunities for improvements in Requests, but those are a trade off of impact to users and limited volunteer time from a couple people. We try to choose what will be the most beneficial when making new releases with the least amount of churn but that doesn't always go as planned.

We've openly discussed the constraints of the current maintainers in previous issues. I don't think anyone is against additional maintainers but many contributors want to come in with a sledge hammer rather than learning the library. Getting to a point of shared understanding requires dedicated time, energy, and patience from both parties. Most of where that's been invested previously has seen low return because it's the internet, people get bored or disappear.

This is a complex part of OSS maintainership, we have both security and stability requirements that need to be maintained when bringing new people onboard. There are also cases where we simply haven't had capacity or shared vision which has lead to other HTTP projects which fill a gap in the Python ecosystem. We're doing what we can with the resources we have.

Requests will continue to serve its current purpose for the foreseeable future. I don't believe we've made claims to do any more than that. We'll try to make improvements as there are straight-forward opportunities and like any OSS project if there are individuals that are consistent and helpful, we'll discuss that with them.

**Comment by rfc-st** [comment]
Hi, @nateprewitt

Thanks for taking the time to read and respond to me. 


Regards,
